#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestDemo.Droid.Resource", IsApplication=true)]

namespace TestDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::TestDemo.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::TestDemo.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::TestDemo.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::TestDemo.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::TestDemo.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::TestDemo.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::TestDemo.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::TestDemo.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::TestDemo.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::TestDemo.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::TestDemo.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::TestDemo.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::TestDemo.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::TestDemo.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::TestDemo.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TestDemo.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::TestDemo.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::TestDemo.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::TestDemo.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TestDemo.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::TestDemo.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::TestDemo.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::TestDemo.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int all_bgCol = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int blue = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int button_bgCol = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int button_txtCol = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int dark_blue = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int end_gradient = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int green = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int h1_txtCol = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int light_blue = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int light_green = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int pink = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int start_gradient = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int text_bgCol = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int text_lineCol = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int text_txtCol = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int vdark_blue = 2131099661;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int button_fontsize = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int button_height = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int button_marg = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int button_margTop = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int button_padding_top = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int button_width = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int h1_fontSize = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int h1_height = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int h1_marg = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int h1_margTop = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int input_fontSize = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int input_height = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int input_width = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int padding_bottom = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int padding_left = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int padding_right = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int padding_top = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int text_fontSize = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int text_marg = 2131165202;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bird_01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bird_02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bird_03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bird_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buterfly_03 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int butterfly_01 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int butterfly_02 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int butterfly_1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int diamond_01 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int diamond_02 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int diamond_03 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int diamond_1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int eagle2_silhouette = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int eagle3_silhouette = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int egg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int generic = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int goal1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int goal2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int goal3 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int goal4 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int goal5 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int goal_placeholder = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int gradient = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int jar_empty = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int jar_stars = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int splash = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05001c
			public const int avatar2 = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int avatar3 = 2131034143;
			
			// aapt resource value: 0x7f05001b
			public const int avatars_container = 2131034139;
			
			// aapt resource value: 0x7f050004
			public const int btnChooseAvatar = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int btnHelloUser = 2131034128;
			
			// aapt resource value: 0x7f050019
			public const int btnInfoUser = 2131034137;
			
			// aapt resource value: 0x7f050025
			public const int btnNewUser = 2131034149;
			
			// aapt resource value: 0x7f050022
			public const int btnTestNewUser = 2131034146;
			
			// aapt resource value: 0x7f050013
			public const int buttonDiary = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int buttonGoals = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int buttonJourney = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int buttonNewUser = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int buttonSetting = 2131034133;
			
			// aapt resource value: 0x7f05000a
			public const int button_home = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int button_newuser = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int buttons = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int container_listview = 2131034124;
			
			// aapt resource value: 0x7f050024
			public const int editTxtNewUser = 2131034148;
			
			// aapt resource value: 0x7f050003
			public const int galleryChooseAvatar = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int h1ChooseAvatar = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int h1HelloUser = 2131034125;
			
			// aapt resource value: 0x7f050017
			public const int h1InfoUser = 2131034135;
			
			// aapt resource value: 0x7f050023
			public const int h1NewUser = 2131034147;
			
			// aapt resource value: 0x7f05000f
			public const int imageChosenAvatar = 2131034127;
			
			// aapt resource value: 0x7f05001a
			public const int imageview_currentavatar = 2131034138;
			
			// aapt resource value: 0x7f050008
			public const int imageview_goal = 2131034120;
			
			// aapt resource value: 0x7f05001d
			public const int imageview_level2 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int imageview_level2_jar = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int imageview_level3 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int imageview_level3_jar = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int textViewGrow = 2131034150;
			
			// aapt resource value: 0x7f050005
			public const int textViewTasks = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int textViewTitle = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int textview_comment = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int textview_title = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int txtHelloUser = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int txtInfoUser = 2131034136;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseAvatarView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChooseTasksView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GoalDetailView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GoalDiaryItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GoalDiaryView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GoalListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GoalListView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HelloNewUserView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int HomeView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int InfoNewUserView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int JourneyView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MyGoalView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int NewUserView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SettingsView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SplashScreen = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
