#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestDemo.Droid.Resource", IsApplication=true)]

namespace TestDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::TestDemo.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::TestDemo.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::TestDemo.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::TestDemo.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::TestDemo.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::TestDemo.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::TestDemo.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::TestDemo.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::TestDemo.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::TestDemo.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::TestDemo.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::TestDemo.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::TestDemo.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::TestDemo.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::TestDemo.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TestDemo.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::TestDemo.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::TestDemo.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::TestDemo.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TestDemo.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::TestDemo.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int all_bgCol = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int blue = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int button_bgCol = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button_txtCol = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int dark_blue = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int end_gradient = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int green = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int h1_txtCol = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int light_blue = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int light_green = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int pink = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int start_gradient = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int text_bgCol = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int text_lineCol = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int text_txtCol = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int vdark_blue = 2131034125;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int button_fontsize = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int button_height = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int button_marg = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int button_margTop = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int button_padding_top = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int button_width = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int h1_fontSize = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int h1_height = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int h1_marg = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int h1_margTop = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int input_fontSize = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int input_height = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int input_width = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public const int padding_bottom = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int padding_left = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int padding_right = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int padding_top = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int text_fontSize = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int text_marg = 2131099666;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_celeste = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_green = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_pink = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int eagle2_silhouette = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int eagle3_silhouette = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int egg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int gradient = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int jar_empty = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int jar_stars = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int avatar2 = 2130968596;
			
			// aapt resource value: 0x7f040017
			public const int avatar3 = 2130968599;
			
			// aapt resource value: 0x7f040013
			public const int avatars_container = 2130968595;
			
			// aapt resource value: 0x7f040004
			public const int btnChooseAvatar = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int btnHelloUser = 2130968584;
			
			// aapt resource value: 0x7f040010
			public const int btnInfoUser = 2130968592;
			
			// aapt resource value: 0x7f040024
			public const int btnNewUser = 2130968612;
			
			// aapt resource value: 0x7f04001d
			public const int btnTestNewUser = 2130968605;
			
			// aapt resource value: 0x7f04000a
			public const int buttonGoals = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int buttonJourney = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int buttonMedal = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int buttonSetting = 2130968589;
			
			// aapt resource value: 0x7f04001b
			public const int button_home = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int button_newuser = 2130968604;
			
			// aapt resource value: 0x7f04001a
			public const int buttons = 2130968602;
			
			// aapt resource value: 0x7f040023
			public const int editTxtNewUser = 2130968611;
			
			// aapt resource value: 0x7f040003
			public const int galleryChooseAvatar = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int h1ChooseAvatar = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int h1HelloUser = 2130968582;
			
			// aapt resource value: 0x7f04000e
			public const int h1InfoUser = 2130968590;
			
			// aapt resource value: 0x7f040022
			public const int h1NewUser = 2130968610;
			
			// aapt resource value: 0x7f040012
			public const int imageview_currentavatar = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int imageview_level2 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int imageview_level2_jar = 2130968598;
			
			// aapt resource value: 0x7f040018
			public const int imageview_level3 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int imageview_level3_jar = 2130968601;
			
			// aapt resource value: 0x7f04001f
			public const int level1 = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int level2 = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int level3 = 2130968609;
			
			// aapt resource value: 0x7f040025
			public const int textViewGrow = 2130968613;
			
			// aapt resource value: 0x7f04001e
			public const int textViewLevel = 2130968606;
			
			// aapt resource value: 0x7f040005
			public const int textViewTasks = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int textViewTitle = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int textview_title = 2130968593;
			
			// aapt resource value: 0x7f040007
			public const int txtHelloUser = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int txtInfoUser = 2130968591;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseAvatarView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChooseTasksView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DetailMedalView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HelloNewUserView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InfoNewUserView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int JourneyView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LevelView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MedalsView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NewUserView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SettingsView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SplashScreen = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
